version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: testapp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testapp
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: testapp-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - 8055:80
    depends_on:
      - postgres
